import { defineConfig } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';

// playwright-bdd generates spec files from .feature + .steps.ts into .features-gen/
const bddTestDir = defineBddConfig({
  features: './tests/**/*.feature',
  steps: ['./steps/**/*.steps.ts', './tests/**/steps/*.steps.ts'],
  importTestFrom: './steps/fixtures.ts',
  disableWarnings: { importTestFrom: true },
});

export default defineConfig({
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 4 : undefined,
  outputDir: 'test-results/',
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on',
  },
  projects: [
    // --- Original .spec.ts tests (will be removed as BDD versions land) ---
    {
      name: 'bandw',
      testDir: './tests',
      use: { baseURL: 'http://localhost:5173' },
      outputDir: 'test-videos/bandw',
      timeout: 15_000,
    },

    // --- BDD .feature tests (generated by playwright-bdd) ---
    {
      name: 'bandw-bdd',
      testDir: bddTestDir,
      use: { baseURL: 'http://localhost:5173' },
      outputDir: 'test-videos/bandw-bdd',
      timeout: 60_000, // BDD tests include SDK setup time
    },
  ],
});
