import { defineConfig } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
import path from 'path';
import fs from 'fs';

const wandbAuthFile = path.join(__dirname, '.auth', 'wandb-storage-state.json');
const hasWandbAuth = fs.existsSync(wandbAuthFile);

// playwright-bdd generates spec files from .feature + .steps.ts into .features-gen/
const bddTestDir = defineBddConfig({
  features: './tests/**/*.feature',
  steps: ['./steps/**/*.steps.ts', './tests/**/steps/*.steps.ts'],
  importTestFrom: './steps/fixtures.ts',
  disableWarnings: { importTestFrom: true },
});

export default defineConfig({
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 4 : undefined,
  outputDir: 'test-results/',
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on',
  },
  projects: [
    // --- Auth setup ---
    {
      name: 'wandb-auth-setup',
      testDir: './tests',
      testMatch: /auth\.setup\.ts/,
    },

    // --- Original .spec.ts tests (will be removed as BDD versions land) ---
    {
      name: 'bandw',
      testDir: './tests',
      use: { baseURL: 'http://localhost:5173' },
      outputDir: 'test-videos/bandw',
      timeout: 15_000,
    },
    {
      name: 'wandb',
      testDir: './tests',
      use: {
        baseURL: 'https://REMOVED',
        ...(hasWandbAuth ? { storageState: wandbAuthFile } : {}),
      },
      outputDir: 'test-videos/wandb',
      timeout: 60_000,
      dependencies: hasWandbAuth ? [] : ['wandb-auth-setup'],
    },

    // --- BDD .feature tests (generated by playwright-bdd) ---
    {
      name: 'bandw-bdd',
      testDir: bddTestDir,
      use: { baseURL: 'http://localhost:5173' },
      outputDir: 'test-videos/bandw-bdd',
      timeout: 60_000, // BDD tests include SDK setup time
    },
    {
      name: 'wandb-bdd',
      testDir: bddTestDir,
      use: {
        baseURL: 'https://REMOVED',
        ...(hasWandbAuth ? { storageState: wandbAuthFile } : {}),
      },
      outputDir: 'test-videos/wandb-bdd',
      timeout: 60_000,
      dependencies: hasWandbAuth ? [] : ['wandb-auth-setup'],
    },
  ],
});
